#ifndef CREATURESTATS_H
#define CREATURESTATS_H

/* TYPES OF CREATURES */
// 0 human, 1 cyberdemon, 2 balrog, 3 elf
#define HUMAN 0
#define CYBERDEMON 1
#define BALROG 2
#define ELF 3

/* INITIAL STRENGTHS OF CREATURES */

#define HUMAN_INIT_STRENGTH 10
#define CYBERDEMON_INIT_STRENGTH 1
#define BALROG_INIT_STRENGTH 2
#define ELF_INIT_STRENGTH 3

#define HUMAN_INIT_HITPOINTS 10
#define CYBERDEMON_INIT_HITPOINTS 1
#define BALROG_INIT_HITPOINTS 2
#define ELF_INIT_HITPOINTS 3



#endif // CREATURESTATS_H
